name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     file_count:
  #       description: 'Number of files to create'
  #       required: true
  #       type: number
  #     file_content:
  #       description: 'Content of the files'
  #       required: true
  #       type: string
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        run: terraform plan -var="file_count=${{ github.event.inputs.file_count }}" -var="file_content='${{ github.event.inputs.file_content }}'"

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var="file_count=${{ fromJSON(github.event.inputs.file_count) }}" -var="file_content='${{ github.event.inputs.file_content }}'"
      
      # - name: 'Terraform Destroy'
      #   run: terraform destroy -auto-approve

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_DEFAULT_REGION: "ap-southeast-2"
