name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of Instance'
        required: true
        type: number
      instance_type:
        description: 'Type of Instance'
        required: true
        type: string
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        run: terraform plan -var="instance_name=${{ github.event.inputs.instance_name }}" -var="instance_type=${{ github.event.inputs.instance_type }}"

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var="instance_name=${{ github.event.inputs.instance_name }}" -var="instance_type=${{ github.event.inputs.instance_type }}"
      
      # - name: 'Terraform Destroy'
      #   run: terraform destroy -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
